# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('hours_per_week', models.SmallIntegerField()),
            ],
        ),
    ]
