# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_profile_type',
            field=models.SmallIntegerField(choices=[(1, b'GM'), (2, b'PM'), (3, b'SM'), (4, b'FTE')], default=employee.models.EmployeeType(4)),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=130),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
